<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="180" started-at="2021-06-08T06:46:43 IST" finished-at="2021-06-08T06:46:43 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="180" started-at="2021-06-08T06:46:43 IST" finished-at="2021-06-08T06:46:43 IST">
      <class name="demogroup.SampleProject.TestDependency">
        <test-method status="PASS" signature="orange()[pri:1, instance:demogroup.SampleProject.TestDependency@22a67b4]" name="orange" duration-ms="18" started-at="2021-06-08T06:46:43 IST" finished-at="2021-06-08T06:46:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orange -->
        <test-method status="PASS" signature="white()[pri:2, instance:demogroup.SampleProject.TestDependency@22a67b4]" name="white" duration-ms="5" started-at="2021-06-08T06:46:43 IST" depends-on-methods="demogroup.SampleProject.TestDependency.orange" finished-at="2021-06-08T06:46:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- white -->
        <test-method status="SKIP" signature="blue()[pri:3, instance:demogroup.SampleProject.TestDependency@22a67b4]" name="blue" duration-ms="9" started-at="2021-06-08T06:46:43 IST" depends-on-methods="demogroup.SampleProject.TestDependency.white" finished-at="2021-06-08T06:46:43 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[blue test is skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: blue test is skipped
at demogroup.SampleProject.TestDependency.blue(TestDependency.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blue -->
        <test-method status="SKIP" signature="green()[pri:4, instance:demogroup.SampleProject.TestDependency@22a67b4]" name="green" duration-ms="1" started-at="2021-06-08T06:46:43 IST" depends-on-methods="demogroup.SampleProject.TestDependency.blue" finished-at="2021-06-08T06:46:43 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDependency.green()[pri:4, instance:demogroup.SampleProject.TestDependency@22a67b4] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDependency.green()[pri:4, instance:demogroup.SampleProject.TestDependency@22a67b4] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- green -->
      </class> <!-- demogroup.SampleProject.TestDependency -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
